// Lista única dos comandos do app sob a ACL do Tauri. Incluída pelo `build.rs`
// (gera `permissions/autogenerated/<comando>.toml`) e pelo teste de `lib.rs`, que
// reprova comando de `generate_handler!` fora daqui e capability desalinhada.
//
// Declarar a lista põe **todos** os comandos do app sob a ACL: o que faltar aqui
// ou na capability é recusado em runtime (`<comando> not allowed`) e o app não
// abre. Comando novo entra em `generate_handler!`, aqui e numa capability.

/// Liberados para todas as janelas (`capabilities/default.json`).
pub const SHARED_COMMANDS: &[&str] = &[
    "get_db_bootstrap",
    "save_file",
    "update_tray_tooltip",
    "update_tray_icon",
    "update_shortcuts",
    "toggle_overlay",
    "start_oauth_server",
    "post_form_json",
    "get_bearer_json",
    "post_bearer_json",
    "get_platform",
    "get_display_server",
    "open_in_browser",
    "open_in_file_manager",
    "check_for_update",
    "download_and_install_update",
    "relaunch_app",
    "start_local_api",
    "stop_local_api",
    "get_local_api_status",
    "get_pending_deep_link_page",
    "get_pending_start_task",
    "get_pending_retroactive_prefill",
    "get_pending_shared_task",
    "open_deep_link",
    "log_frontend",
    "backup_db_to_drive",
];

/// Ponte da API local: só a janela `main` responde pelo app
/// (`capabilities/local-api-bridge.json`). Um overlay que chamasse
/// `local_api_respond` responderia requisições que não executou.
pub const MAIN_ONLY_COMMANDS: &[&str] = &["local_api_respond", "local_api_bridge_ready"];
